"use client"


/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8GEbGXlOFrg
 */
import Link from "next/link"
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Button } from "@nextui-org/react"
import { useEffect, type SVGProps } from "react"
import axios from "axios"
import { useDocumentContext } from "@/lib/context/DocumentContext"
import { env } from "@/env"
import { api } from "@/trpc/react"
import { cn } from "@/lib/utils"



export function PriceCards() {
  const {customerId} = useDocumentContext()
  const {mutate, data:subscriptionRes, isLoading:isSuubscribing} = api.user.subscribeToPlan.useMutation()
  async function handleSignUp() {
    console.log('custId', customerId);
    
    mutate({customerCode:customerId!})
  }

  useEffect(() => {
    if(subscriptionRes?.success) {
     window.location.assign(subscriptionRes.success_url!) 
    }
  },[subscriptionRes?.success])

  return (
    <main className="w-full py-12 md:py-24 lg:py-32">
      {/* <header className="flex h-20 w-full shrink-0 items-center px-4 md:px-6">
        <Link className="mr-6" href="#">
          <FileIcon className="h-6 w-6" />
          <span className="sr-only">DocCreator</span>
        </Link>
        <nav className="ml-auto w-[150px]">
          <Link href="#">Home</Link>
          <Link href="#">About</Link>
          <Link href="#">Contact</Link>
        </nav>
      </header> */}
      <section className="container px-4 md:px-6">
        <div className="text-center space-y-3">
          <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Pricing</h1>
          <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
            Choose the plan that suits your needs. Upgrade, downgrade, or cancel anytime.
          </p>
        </div>
        <div className="grid items-start gap-6 md:grid-cols-2 lg:gap-12 xl:gap-16 mt-8">
          <Card>
            <CardHeader>
              <CardTitle>Pro Plan</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                <StarIcon className="h-10 w-10 text-yellow-400 mx-auto" />
                <p className="text-gray-500 dark:text-gray-400">
                  Get unlimited access to all features and resources. Ideal for professional creators and teams.
                </p>
                <ul className="list-disc list-inside text-gray-500 dark:text-gray-400">
                  <li>Unlimited documents</li>
                  <li>Premium templates</li>
                  <li>Priority support</li>
                </ul>
                <p className="font-bold text-2xl">{}</p>
              </div>
            </CardContent>
            <CardFooter>
              <Button onClick={handleSignUp} isLoading={isSuubscribing} className={cn('w-full h-10 items-center justify-center rounded-md bg-blue-500 text-white')}>
                Sign Up for Pro
              </Button>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Free Plan</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                <CloudIcon className="h-10 w-10 text-blue-400 mx-auto" />
                <p className="text-gray-500 dark:text-gray-400">
                  Start creating documents for free. Upgrade anytime for more features and resources.
                </p>
                <ul className="list-disc list-inside text-gray-500 dark:text-gray-400">
                  <li>Up to 10 documents</li>
                  <li>Basic templates</li>
                  <li>Email support</li>
                </ul>
                <p className="font-bold text-2xl">Free</p>
              </div>
            </CardContent>
            <CardFooter>
              <Button  className="w-full h-10 items-center justify-center rounded-md border border-gray-200 bg-white text-black">
                Sign Up for Free
              </Button>
            </CardFooter>
          </Card>
        </div>
      </section>
    </main>
  )
}


function FileIcon(props:SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.5 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7.5L14.5 2z" />
      <polyline points="14 2 14 8 20 8" />
    </svg>
  )
}




function StarIcon(props:SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}


function CloudIcon(props:SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z" />
    </svg>
  )
}
